Repository Metanet-Team3/final-repo, pull requests merged in 2024-01, with the labels that each got.

#8 #7/회원가입
  src/main/resources/css/header.css
Labels: 🎨 For: Frontend, 👈 Priority: Middle

#14 Lala9663/#2/signup
  pom.xml
  src/main/java/com/meta/metaway/config/SecurityConfig.java
  src/main/java/com/meta/metaway/jwt/JWTFilter.java
  src/main/java/com/meta/metaway/jwt/JWTUtil.java
  src/main/java/com/meta/metaway/jwt/LoginFilter.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/java/com/meta/metaway/user/dao/UserRepository.java
  src/main/java/com/meta/metaway/user/dto/CustomUserDetails.java
  src/main/java/com/meta/metaway/user/dto/JoinDTO.java
  src/main/java/com/meta/metaway/user/model/Authority.java
  src/main/java/com/meta/metaway/user/model/User.java
  src/main/java/com/meta/metaway/user/service/CustomUserDetailsService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/mapper/UserMapper.xml
Labels: ⚙ For: API, ✨ For: Backend, 👆 Priority: High, ✅ Status: Complete, 💻 Type: Feature

#15 refactor 불필요한 부분 삭제 및 수정
  src/main/java/com/meta/metaway/config/SecurityConfig.java
  src/main/resources/application.properties
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, 🛠 Type: Config

#16 Feat: 회원 정보 api 구현
  src/main/java/com/meta/metaway/jwt/JWTFilter.java
  src/main/java/com/meta/metaway/product/dao/IProductRepository.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/CustomUserDetailsService.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, ✅ Status: Complete, 💻 Type: Feature

#17 상품 조회 이미지 표시 구현
  src/main/java/com/meta/metaway/product/controller/ProductController.java
  src/main/java/com/meta/metaway/product/dao/IProductRepository.java
  src/main/java/com/meta/metaway/product/model/Product.java
  src/main/java/com/meta/metaway/product/service/IProductService.java
  src/main/java/com/meta/metaway/product/service/ProductService.java
  src/main/resources/mapper/product/ProductMapper.xml
  src/main/resources/templates/product/upload.html
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, 💻 Type: Feature

#19 상품 조회 백엔드 빠진 부분 추가
  src/main/java/com/meta/metaway/product/model/Function.java
  src/main/resources/templates/product/productDetail.html
Labels: ✨ For: Backend

#20 비밀번호 체크 api
  src/main/java/com/meta/metaway/config/SecurityConfig.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: ⚙ For: API, ✨ For: Backend, 👇 Priority: Low, ✅ Status: Complete, 💻 Type: Feature

#22 front header, footer - 수정, main - 진행
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/join.css
  src/main/resources/static/css/login.css
  src/main/resources/static/images/coway8.png
  src/main/resources/static/images/coway9.png
  src/main/resources/templates/board/main.html
  src/main/resources/templates/include/footer.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/main.html
  src/main/resources/templates/member/join.html
  src/main/resources/templates/member/login.html
Labels: 🎨 For: Frontend, 👈 Priority: Middle, 💻 Type: Feature

#27 Feat: 직원 근무지 api
  src/main/java/com/meta/metaway/jwt/JWTFilter.java
  src/main/java/com/meta/metaway/jwt/LoginFilter.java
  src/main/java/com/meta/metaway/user/controller/StaffController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IStaffRepository.java
  src/main/java/com/meta/metaway/user/model/Staff.java
  src/main/java/com/meta/metaway/user/service/IStaffService.java
  src/main/java/com/meta/metaway/user/service/StaffService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/staff/StaffMapper.xml
Labels: ⚙ For: API, ✨ For: Backend, 👆 Priority: High, ✅ Status: Complete, 💻 Type: Feature

#30 refactor: 회원 수정 반영 안되는거 수정
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: ⚙ For: API, ✨ For: Backend, 👆 Priority: High, ✅ Status: Complete, 🔨 Type: Refactor

#37 Feat: 프론트랑 연결
  src/main/java/com/meta/metaway/config/SecurityConfig.java
  src/main/java/com/meta/metaway/config/WebMvcConfig.java
  src/main/java/com/meta/metaway/jwt/CustomUsernamePasswordAuthenticationFilter.java
  src/main/java/com/meta/metaway/jwt/JWTFilter.java
  src/main/java/com/meta/metaway/jwt/LoginFilter.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/controller/UserController2.java
  src/main/java/com/meta/metaway/user/dao/IBasketRepository.java
  src/main/java/com/meta/metaway/user/dto/CustomUserDetails.java
  src/main/java/com/meta/metaway/user/model/Basket.java
  src/main/java/com/meta/metaway/user/service/CustomUserDetailsService.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/BasketMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/static/js/axiosInstacnce.js
  src/main/resources/templates/index.html
  src/main/resources/templates/join.html
  src/main/resources/templates/member/join2.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/profile.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👆 Priority: High, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#38 Feat: front main 수정 / cody, drive view
  src/main/resources/static/css/co_main.css
  src/main/resources/static/css/dr_main.css
  src/main/resources/static/css/footer.css
  src/main/resources/static/css/index.css
  src/main/resources/static/images/bgwater.jpeg
  src/main/resources/static/images/bgwater.jpg
  src/main/resources/static/images/coway10.png
  src/main/resources/static/images/coway11.jpeg
  src/main/resources/static/images/coway12.jpeg
  src/main/resources/static/images/coway6.png
  src/main/resources/static/images/coway9.jpeg
  src/main/resources/static/images/eco.png
  src/main/resources/static/images/maintenace.png
  src/main/resources/static/images/quality.png
  src/main/resources/static/js/includeHTML.js
  src/main/resources/templates/include/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/staff/co_main.html
  src/main/resources/templates/staff/dri_main.html
Labels: 🎨 For: Frontend, 👈 Priority: Middle, 💻 Type: Feature

#41 Feat: staff 생성, index 수정
  src/main/java/com/meta/metaway/staff/controller/StaffController.java
  src/main/java/com/meta/metaway/staff/dao/IStaffRepository.java
  src/main/java/com/meta/metaway/staff/dto/StaffDTO.java
  src/main/java/com/meta/metaway/staff/model/staff.java
  src/main/java/com/meta/metaway/staff/service/IStaffService.java
  src/main/java/com/meta/metaway/staff/service/StaffService.java
  src/main/resources/templates/include/header.html
  src/main/resources/templates/index.html
Labels: ✨ For: Backend, 🎨 For: Frontend, 👈 Priority: Middle

#44 Feat: 프론트에 토큰 연결 구현
  src/main/java/com/meta/metaway/config/WebMvcConfig.java
  src/main/java/com/meta/metaway/jwt/LoginFilter.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/resources/templates/member/profile.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👆 Priority: High, ✅ Status: Complete, 💻 Type: Feature

#47 Lala9663/#45/refactoring
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/java/com/meta/metaway/user/controller/UserController2.java
  src/main/resources/templates/index.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/user/join.html
  src/main/resources/templates/user/join2.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
Labels: ⚙ For: API, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete, 🔨 Type: Refactor

#49 Refactor: 토큰에 정보 추가
  src/main/java/com/meta/metaway/jwt/JWTUtil.java
  src/main/java/com/meta/metaway/jwt/LoginFilter.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/java/com/meta/metaway/user/dto/CustomUserDetails.java
  src/main/resources/mapper/user/UserMapper.xml
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, ✅ Status: Complete, 🔨 Type: Refactor

#53 Feat: 회원 관련 기능 구현
  src/main/java/com/meta/metaway/multiClass/MultiClass.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/templates/user/delete.html
  src/main/resources/templates/user/updateProfile.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete, 💻 Type: Feature, 🔨 Type: Refactor

#58 장바구니 담기 기능 추가
  src/main/java/com/meta/metaway/order/controller/OrderController.java
  src/main/java/com/meta/metaway/product/controller/ProductController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IBasketRepository.java
  src/main/java/com/meta/metaway/user/model/Basket.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/BasketMapper.xml
  src/main/resources/templates/product/productDetail.html
Labels: ⚙ For: API

#60 상품 구매시 부분 HTML 에러 부분 수정
  src/main/resources/templates/product/product.html
Labels: 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete, 🐞 Type: Bug

#61 주문 리스트 주문으로 조회
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/templates/user/orderlist.html
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, ✅ Status: Complete, 💻 Type: Feature

#62 유저 서비스 장바구니 이미지 스트링 변경기능 추가
  src/main/java/com/meta/metaway/user/service/UserService.java
Labels: ⚙ For: API, 🔨 Type: Refactor

#63 Feat: 주문 List
  src/main/java/com/meta/metaway/order/model/OrderDetail.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/templates/user/orderDetailList.html
  src/main/resources/templates/user/orderlist.html
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#64 refactor: 중복 제거
  src/main/java/com/meta/metaway/user/service/UserService.java
Labels: ⚙ For: API, 🐞 Type: Bug, 🔨 Type: Refactor

#66 Feat: 시큐리티 계층 권한 추가
  src/main/java/com/meta/metaway/config/SecurityConfig.java
Labels: ⚙ For: API, ✨ For: Backend, 👇 Priority: Low, 💻 Type: Feature, 🔨 Type: Refactor

#73 HTML / CSS 완성도 수정
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/order.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/productDetail.css
  src/main/resources/templates/order/order.html
  src/main/resources/templates/product/product.html
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/user/basket.html
Labels: 🎨 For: Frontend, 👈 Priority: Middle

#74 주문시 오더 수량 0으로 들어가는 부분 수정
  src/main/resources/mapper/order/OrderMapper.xml
  src/main/resources/templates/order/order.html
Labels: ✨ For: Backend

#76 feat/#23/staff_상품_구매_목록
  src/main/java/com/meta/metaway/schedule/controller/ScheduleController.java
  src/main/java/com/meta/metaway/staff/controller/StaffController.java
  src/main/resources/mapper/staff/StaffMapper.xml
  src/main/resources/static/css/index.css
  src/main/resources/static/css/join.css
  src/main/resources/static/css/join2.css
  src/main/resources/static/css/login.css
  src/main/resources/static/images/address.png
  src/main/resources/static/images/birth.png
  src/main/resources/static/images/email.png
  src/main/resources/static/images/phone.png
  src/main/resources/static/images/pwd.png
  src/main/resources/templates/include/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/staff/co_main.html
  src/main/resources/templates/staff/codymain.html
  src/main/resources/templates/staff/drivemain.html
  src/main/resources/templates/user/join.html
  src/main/resources/templates/user/login.html
Labels: 🎨 For: Frontend

#78 Feat: 비밀번호 변경 , 수정 api, 마이페이지 수정
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/dto/ChangePasswordDTO.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateProfile.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#80 Feat: 이메일 인증
  pom.xml
  src/main/java/com/meta/metaway/config/EmailConfig.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dto/EmailRequestDTO.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/MailSendService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/user/join.html
Labels: ⚙ For: API, ✨ For: Backend, 👇 Priority: Low, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#81 Revert "Feat: 이메일 인증"
  pom.xml
  src/main/java/com/meta/metaway/config/EmailConfig.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dto/EmailRequestDTO.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/MailSendService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/user/join.html
Labels: ⚙ For: API, 🐞 Type: Bug

#83 Feat: 반납/해지/환불 신청/취소 렌탈 연장 기능 추가
  src/main/java/com/meta/metaway/order/controller/OrderController.java
  src/main/java/com/meta/metaway/order/dao/IOrderRepository.java
  src/main/java/com/meta/metaway/order/model/Order.java
  src/main/java/com/meta/metaway/order/service/IOrderService.java
  src/main/java/com/meta/metaway/order/service/OrderService.java
  src/main/java/com/meta/metaway/returned/controller/ReturnedController.java
  src/main/java/com/meta/metaway/returned/dao/IRetunedRepository.java
  src/main/java/com/meta/metaway/returned/model/Returned.java
  src/main/java/com/meta/metaway/returned/service/IReturnedService.java
  src/main/java/com/meta/metaway/returned/service/RetrunedService.java
  src/main/resources/mapper/order/OrderMapper.xml
  src/main/resources/mapper/product/ProductMapper.xml
  src/main/resources/mapper/returned/ReturnedMapper.xml
  src/main/resources/templates/order/order.html
  src/main/resources/templates/product/productDetail.html
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, ✅ Status: Complete

#84 HTML 상단바 표시 문제 해결
  src/main/java/com/meta/metaway/returned/controller/ReturnedController.java
  src/main/resources/templates/include/header.html
  src/main/resources/templates/product/product.html
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/product/productInsert.html
  src/main/resources/templates/product/productUpdate.html
  src/main/resources/templates/staff/codymain.html
  src/main/resources/templates/staff/drive.html
  src/main/resources/templates/staff/drivemain.html
  src/main/resources/templates/user/basket.html
  src/main/resources/templates/user/login.html
Labels: 🎨 For: Frontend, 👆 Priority: High, 👇 Priority: Low, ✅ Status: Complete

#88 권한 쿠키 추가 / 헤더에 권한에 따른 변화 추가
  src/main/java/com/meta/metaway/jwt/LoginFilter.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/resources/templates/include/header.html
Labels: ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete

#89 /user/basket - front 수정완료 ...
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/order.css
  src/main/resources/static/css/orderdetail.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/images/card.png
  src/main/resources/static/images/x.jpg
  src/main/resources/templates/include/header.html
  src/main/resources/templates/order/order.html
  src/main/resources/templates/staff/drivemain.html
  src/main/resources/templates/user/basket.html
  src/main/resources/templates/user/orderDetailList.html
  src/main/resources/templates/user/profile.html
Labels: 🎨 For: Frontend

#91 헤더 이미지 안나오는 문제 해결 / 장바구니 문구 수정
  src/main/resources/templates/include/header.html
  src/main/resources/templates/product/productDetail.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, ✅ Status: Complete

#90 Feat: 판매 랭킹 api
  src/main/java/com/meta/metaway/admin/controller/AdminController.java
  src/main/java/com/meta/metaway/admin/dao/IAdminRepository.java
  src/main/java/com/meta/metaway/admin/dto/SoldRankDTO.java
  src/main/java/com/meta/metaway/admin/service/AdminService.java
  src/main/java/com/meta/metaway/admin/service/IAdminService.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/productRank.html
  src/main/resources/templates/admin/productRankWithImage.html
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, ✅ Status: Complete, 💻 Type: Feature

#92 쿠키가 남는 문제 해결, 상품창 이미지 추가, 헤더 숨김 옵션 변경
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/resources/static/images/productMain.jpg
  src/main/resources/templates/include/header.html
  src/main/resources/templates/product/product.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, ✅ Status: Complete

#94 Feat: 관리자가 필요한 기능들
  src/main/java/com/meta/metaway/admin/controller/AdminController.java
  src/main/java/com/meta/metaway/admin/dao/IAdminRepository.java
  src/main/java/com/meta/metaway/admin/service/AdminService.java
  src/main/java/com/meta/metaway/admin/service/IAdminService.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/getTotalUser.html
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#95 혜민이 부분 대신 커밋
  src/main/resources/static/css/login.css
  src/main/resources/static/css/product.css
  src/main/resources/templates/product/product.html
Labels: 🎨 For: Frontend

#96 Feat: 빠진 DTO 부분 추가
  src/main/java/com/meta/metaway/admin/dto/TotalSaleDTO.java
  src/main/java/com/meta/metaway/admin/dto/UserCountDTO.java
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, 💻 Type: Feature

#97 Feat: 오류 확인
  pom.xml
  src/main/java/com/meta/metaway/config/EmailConfig.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dto/EmailRequestDTO.java
  src/main/java/com/meta/metaway/user/dto/JoinDTO.java
  src/main/java/com/meta/metaway/user/model/User.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/MailSendService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/templates/admin/getTotalSold.html
  src/main/resources/templates/user/emailVerification.html
  src/main/resources/templates/user/join.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete

#98 feat: 대시보드로 몰아넣기 여기서 작업 시작
  src/main/java/com/meta/metaway/admin/controller/AdminController.java
  src/main/resources/templates/admin/dashboard.html
Labels: 🎨 For: Frontend, 👈 Priority: Middle, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#101 오더 매퍼, 프로덕트 매퍼, 리턴드 매퍼가 제대로 동작하지 않는 문제 해결
  src/main/resources/mapper/order/OrderMapper.xml
  src/main/resources/mapper/product/ProductMapper.xml
  src/main/resources/mapper/returned/ReturnedMapper.xml
Labels: 🎨 For: Frontend, 🔨 Type: Refactor

#102 front - productdetail, insert, update
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/join.css
  src/main/resources/static/css/order.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/productDetail.css
  src/main/resources/static/css/productInsert.css
  src/main/resources/static/css/productUpdate.css
  src/main/resources/static/css/profile.css
  src/main/resources/static/images/product1.jpg
  src/main/resources/templates/order/order.html
  src/main/resources/templates/product/product.html
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/product/productInsert.html
  src/main/resources/templates/product/productUpdate.html
  src/main/resources/templates/user/join.html
Labels: 🎨 For: Frontend, 💻 Type: Feature, 🔨 Type: Refactor

#100 Feat: 스케줄러, redis
  pom.xml
  src/main/java/com/meta/metaway/WaterApplication.java
  src/main/java/com/meta/metaway/admin/controller/AdminController.java
  src/main/java/com/meta/metaway/admin/controller/RedisController.java
  src/main/java/com/meta/metaway/admin/dao/IAdminRepository.java
  src/main/java/com/meta/metaway/admin/model/Visitor.java
  src/main/java/com/meta/metaway/admin/scheduler/VisitorScheduler.java
  src/main/java/com/meta/metaway/admin/service/AdminService.java
  src/main/java/com/meta/metaway/admin/service/IAdminService.java
  src/main/java/com/meta/metaway/config/RedisConfig.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/resources/application.properties
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/viewCount.html
Labels: ⚙ Type: Setting, ⚙ For: API, ✨ For: Backend, 👆 Priority: High, ✅ Status: Complete, 💻 Type: Feature

#107 Feat: 관리자 대시보드
  src/main/java/com/meta/metaway/admin/controller/AdminController.java
  src/main/java/com/meta/metaway/admin/dao/IAdminRepository.java
  src/main/java/com/meta/metaway/admin/service/AdminService.java
  src/main/java/com/meta/metaway/admin/service/IAdminService.java
  src/main/java/com/meta/metaway/staff/dto/StaffDTO.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/static/css/admin/assets/css/style.css
  src/main/resources/static/css/admin/assets/imgs/customer01.jpg
  src/main/resources/static/css/admin/assets/imgs/customer02.jpg
  src/main/resources/static/css/admin/assets/imgs/profile.jpg
  src/main/resources/static/css/admin/assets/js/main.js
  src/main/resources/static/images/machine1.png
  src/main/resources/static/images/machine2.png
  src/main/resources/static/images/machine3.png
  src/main/resources/templates/admin/adminview.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#108 오더 매퍼 상품 등록시 문제 해결
  src/main/java/com/meta/metaway/order/model/Order.java
  src/main/java/com/meta/metaway/product/model/Contract.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/order/OrderMapper.xml
  src/main/resources/mapper/product/ProductMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/static/css/myOrder.css
  src/main/resources/templates/user/order.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend

#109 관리자/프로필 비동기 처리
  src/main/java/com/meta/metaway/staff/controller/StaffController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/static/css/admin/adminorderdetail.css
  src/main/resources/static/css/admin/assets/css/style.css
  src/main/resources/static/css/admin/style.css
  src/main/resources/static/css/basket.css
  src/main/resources/static/css/dr_main.css
  src/main/resources/static/css/join.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/order.css
  src/main/resources/static/css/profile.css
  src/main/resources/templates/admin/adminview.html
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/searchorder.html
  src/main/resources/templates/product/productInsert.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/orderDetailList.html
  src/main/resources/templates/user/profile.html
Labels: 🎨 For: Frontend

#110 Feat: AOP 적용 및 log 파일 추가 및 설정
  pom.xml
  src/main/java/com/meta/metaway/aspect/PerformanceMonitoringAspect.java
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/resources/application.properties
  src/main/resources/logback/log-back.xml
Labels: ⚙ Type: Setting, ⚙ For: API, 👆 Priority: High, ✅ Status: Complete, 💪 Type: Enhancement, 💻 Type: Feature

#111 feat: 이번달 총 구매 합 구현, 대시보드
  src/main/java/com/meta/metaway/admin/controller/AdminController.java
  src/main/java/com/meta/metaway/admin/dao/IAdminRepository.java
  src/main/java/com/meta/metaway/admin/service/AdminService.java
  src/main/java/com/meta/metaway/admin/service/IAdminService.java
  src/main/java/com/meta/metaway/order/dto/OrderDTO.java
  src/main/resources/application.properties
  src/main/resources/logback/log-back.xml
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/static/css/admin/assets/css/style.css
  src/main/resources/templates/admin/adminview.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, ✅ Status: Complete, 💻 Type: Feature, 🔨 Type: Refactor

#116 오류 추가 표시
  src/main/resources/templates/admin/adminview.html
Labels: 🎨 For: Frontend, 👇 Priority: Low, 🔨 Type: Refactor

#117 변경사항 적용
  src/main/resources/templates/admin/adminview.html
Labels: 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete, 🐞 Type: Bug

#118 오더 디테일 백엔드/프론트 구현
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/static/css/orderDetail.css
  src/main/resources/static/css/orderdetail.css
  src/main/resources/templates/user/order.html
  src/main/resources/templates/user/orderDetail.html
  src/main/resources/templates/user/orderDetailList.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 🙋‍♂️ Status: In Progress

#119 오더 디테일 자바스크립트 / 리턴관련 조정
  src/main/java/com/meta/metaway/returned/dao/IRetunedRepository.java
  src/main/java/com/meta/metaway/returned/service/RetrunedService.java
  src/main/resources/mapper/returned/ReturnedMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/static/css/orderDetail.css
  src/main/resources/templates/user/orderDetail.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👈 Priority: Middle

#121 근무지 입력, 수정
  src/main/java/com/meta/metaway/admin/dto/SoldRankDTO.java
  src/main/java/com/meta/metaway/staff/controller/StaffController.java
  src/main/java/com/meta/metaway/staff/dao/IStaffRepository.java
  src/main/java/com/meta/metaway/staff/service/IStaffService.java
  src/main/java/com/meta/metaway/staff/service/StaffService.java
  src/main/resources/mapper/staff/StaffMapper.xml
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/getTotalSold.html
  src/main/resources/templates/admin/getTotalUser.html
  src/main/resources/templates/admin/productRankWithImage.html
  src/main/resources/templates/admin/viewCount.html
  src/main/resources/templates/staff/createWorkPlace.html
  src/main/resources/templates/staff/updateWorkPlace.html
Labels: ⚙ For: API, ✨ For: Backend, 👈 Priority: Middle, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#122 반납 기능/반납 취소 기능 구현 완료.
  src/main/java/com/meta/metaway/product/model/Contract.java
  src/main/java/com/meta/metaway/returned/controller/ReturnedController.java
  src/main/java/com/meta/metaway/returned/dao/IReturnedRepository.java
  src/main/java/com/meta/metaway/returned/service/RetrunedService.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/mapper/order/OrderMapper.xml
  src/main/resources/mapper/returned/ReturnedMapper.xml
  src/main/resources/templates/user/orderDetail.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, ✅ Status: Complete

#124 adminview.html 수정
  src/main/java/com/meta/metaway/staff/dto/VisitDateUpdateRequest.java
  src/main/resources/static/css/admin/adminorderdetail.css
  src/main/resources/static/css/admin/assets/css/style.css
  src/main/resources/static/css/co_main.css
  src/main/resources/static/images/return.png
  src/main/resources/templates/admin/adminview.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/product/productInsert.html
  src/main/resources/templates/staff/codymain.html
  src/main/resources/templates/staff/drivemain.html
  src/main/resources/templates/user/orderDetail.html
  src/main/resources/templates/user/profile.html
Labels: 🎨 For: Frontend

#125 productDetail 기능 / 버그 문제 해결
  src/main/resources/static/css/productDetail.css
  src/main/resources/templates/product/productDetail.html
Labels: ⚙ For: API, 🎨 For: Frontend, ✅ Status: Complete

#126 회원가입 이동이 안되는 문제 해결
  src/main/resources/templates/user/login.html
Labels: ⚙ For: API, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete

#127 페이지 수정
  src/main/resources/templates/admin/adminview.html
Labels: 🎨 For: Frontend

#131 product 이미지 수정
  src/main/resources/static/css/admin/paging.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/productDetail.css
  src/main/resources/static/images/coway16.png
  src/main/resources/static/images/coway17.png
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/rentalmanage.html
  src/main/resources/templates/include/footer.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/include/paging.html
  src/main/resources/templates/index.html
  src/main/resources/templates/product/product.html
Labels: 🎨 For: Frontend

#132 상품 자세히 보기 전환버튼 누른 후 장바구니 담는 기능 추가
  src/main/resources/templates/product/productDetail.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend

#133 관리자 페이지 수정
  src/main/java/com/meta/metaway/user/dao/IUserRepository.java
  src/main/java/com/meta/metaway/user/service/IUserService.java
  src/main/java/com/meta/metaway/user/service/UserService.java
  src/main/resources/mapper/user/UserMapper.xml
  src/main/resources/static/css/join.css
  src/main/resources/templates/admin/adminview.html
  src/main/resources/templates/user/join.html
Labels: 🎨 For: Frontend

#134 HTML ADMIN PAGE 변경
  src/main/resources/static/css/admin/style.css
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/rentalmanage.html
  src/main/resources/templates/admin/returndetail.html
  src/main/resources/templates/user/orderDetail.html
Labels: ⚙ For: API, 🎨 For: Frontend, 👈 Priority: Middle, ✅ Status: Complete

#135 feat: 로그인 유효성 검사
  src/main/java/com/meta/metaway/user/controller/AuthController.java
  src/main/java/com/meta/metaway/user/dto/JoinDTO.java
  src/main/resources/templates/user/join.html
  src/main/resources/templates/user/login.html
Labels: ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete, 💻 Type: Feature

#137 상품, 상품 디테일 부분 단순문제 해결
  src/main/resources/static/css/order.css
  src/main/resources/static/css/orderDetail.css
  src/main/resources/static/css/product.css
  src/main/resources/static/css/productDetail.css
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/rentalmanage.html
  src/main/resources/templates/admin/returndetail.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/product/product.html
  src/main/resources/templates/product/productDetail.html
  src/main/resources/templates/user/orderDetail.html
  src/main/resources/templates/user/profile.html
Labels: 🎨 For: Frontend, 👈 Priority: Middle, ✅ Status: Complete

#140 주문시 얼럿창 생성하여 주문완료 메세지 출력
  src/main/resources/templates/order/order.html
Labels: 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete

#142 Feat: 에러페이지 추가
  src/main/java/com/meta/metaway/aspect/PerformanceMonitoringAspect.java
  src/main/java/com/meta/metaway/global/GlobalExceptionHandler.java
  src/main/java/com/meta/metaway/global/MultiClass.java
  src/main/resources/application.properties
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/error.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👈 Priority: Middle, ✅ Status: Complete, 💻 Type: Feature

#143 직원 리스트 다시 부활 + 로그인 푸터 제거
  src/main/resources/templates/admin/adminview.html
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/rentalmanage.html
  src/main/resources/templates/admin/returndetail.html
  src/main/resources/templates/admin/staffmanage.html
  src/main/resources/templates/user/login.html
Labels: ⚙ For: API, 🎨 For: Frontend, 👈 Priority: Middle, ✅ Status: Complete

#144 멀티클래스 수정 + 값 보이기 수정
  src/main/java/com/meta/metaway/order/controller/OrderController.java
  src/main/java/com/meta/metaway/staff/controller/StaffController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/templates/admin/adminview.html
Labels: ✨ For: Backend, 🎨 For: Frontend

#145 스크립트 함수 빠진거 추가
  src/main/resources/templates/user/join.html
Labels: 🎨 For: Frontend, 👆 Priority: High, ✅ Status: Complete, 🐞 Type: Bug, 🔨 Type: Refactor

#146 장바구니 약정 총 가격 표시기능 추가
  src/main/resources/static/css/basket.css
  src/main/resources/templates/user/basket.html
Labels: 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete

#148 뷰페이지 값 변경
  src/main/resources/templates/admin/adminview.html
Labels: 🎨 For: Frontend, 👇 Priority: Low

#150 드라이버 베송/반납기능 구현
  src/main/java/com/meta/metaway/staff/controller/StaffController.java
  src/main/java/com/meta/metaway/staff/dao/IStaffRepository.java
  src/main/java/com/meta/metaway/staff/dto/StaffScheduleDTO.java
  src/main/java/com/meta/metaway/staff/service/IStaffService.java
  src/main/java/com/meta/metaway/staff/service/StaffService.java
  src/main/resources/mapper/staff/StaffMapper.xml
  src/main/resources/templates/order/order.html
  src/main/resources/templates/staff/drive-todo.html
Labels: ✨ For: Backend, 🎨 For: Frontend, 👆 Priority: High, ✅ Status: Complete

#151 feat: 코디나 드라이버일때 입력 받는 창 만들기 수정필요함
  src/main/java/com/meta/metaway/staff/service/IStaffService.java
  src/main/java/com/meta/metaway/staff/service/StaffService.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/templates/staff/createWorkPlace.html
  src/main/resources/templates/user/createWorkPlace.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👈 Priority: Middle, 🙋‍♂️ Status: In Progress, 💻 Type: Feature

#153 Front - 프로필 비동기x 동기o 완성
  src/main/resources/static/css/order.css
  src/main/resources/static/css/orderDetail.css
  src/main/resources/templates/user/order.html
  src/main/resources/templates/user/orderDetail.html
  src/main/resources/templates/user/profile.html
Labels: 🎨 For: Frontend

#154 refactor: 불필요한 import문 삭제
  src/main/java/com/meta/metaway/admin/controller/AdminController.java
  src/main/java/com/meta/metaway/order/controller/OrderController.java
  src/main/java/com/meta/metaway/product/controller/ProductController.java
  src/main/java/com/meta/metaway/returned/controller/ReturnedController.java
  src/main/java/com/meta/metaway/staff/controller/StaffController.java
  src/main/java/com/meta/metaway/user/controller/UserController.java
Labels: 👇 Priority: Low, ✅ Status: Complete, 🔨 Type: Refactor

#155 오더, 오더디테일 문제 해결
  src/main/resources/templates/user/order.html
  src/main/resources/templates/user/orderDetail.html
Labels: 🎨 For: Frontend, 👈 Priority: Middle, ✅ Status: Complete

#156 사소한 HTML 부분 수정
  src/main/resources/static/css/order.css
  src/main/resources/templates/user/order.html
  src/main/resources/templates/user/orderDetail.html
Labels: ⚙ For: API, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete

#157 사소한 HTML 부분 수정 2
  src/main/resources/static/css/orderDetail.css
  src/main/resources/templates/user/orderDetail.html
  src/main/resources/templates/user/profile.html
Labels: ⚙ For: API, 🎨 For: Frontend

#158 HTML 상품 등록 경로 수정
  src/main/resources/static/css/productInsert.css
  src/main/resources/templates/admin/adminview.html
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/rentalmanage.html
  src/main/resources/templates/admin/returndetail.html
  src/main/resources/templates/admin/searchorder.html
  src/main/resources/templates/admin/staffmanage.html
  src/main/resources/templates/staff/drive-todo.html
Labels: ⚙ For: API, 🎨 For: Frontend

#159 관리자페이지 제약조건 변경 및 토큰 입력값 오탈자 수정
  src/main/java/com/meta/metaway/jwt/LoginFilter.java
  src/main/resources/templates/admin/adminview.html
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/rentalmanage.html
  src/main/resources/templates/admin/returndetail.html
  src/main/resources/templates/admin/searchorder.html
  src/main/resources/templates/admin/staffmanage.html
  src/main/resources/templates/include/header.html
  src/main/resources/templates/product/productInsert.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend

#160 adminPage 제약조건 변경
  src/main/resources/static/css/myOrder.css
  src/main/resources/templates/admin/adminview.html
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/rentalmanage.html
  src/main/resources/templates/admin/returndetail.html
  src/main/resources/templates/admin/searchorder.html
  src/main/resources/templates/admin/staffmanage.html
  src/main/resources/templates/product/productInsert.html
  src/main/resources/templates/staff/drive-todo.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend

#161 이름 고민 제거
  src/main/resources/templates/include/header.html
Labels: 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete

#162 css 수정
  src/main/resources/static/css/admin/adminorderdetail.css
  src/main/resources/static/css/admin/style.css
  src/main/resources/static/css/join.css
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/admin/searchstaff.html
  src/main/resources/templates/admin/staffmanage.html
Labels: 🎨 For: Frontend

#163 Refactor: 주소요청값 변경
  src/main/java/com/meta/metaway/order/model/Order.java
  src/main/resources/mapper/order/OrderMapper.xml
  src/main/resources/static/css/order.css
  src/main/resources/templates/order/order.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, 🙋‍♂️ Status: In Progress, 🔨 Type: Refactor

#164 refactor: 대시보드에서 주소지 값 나오는거 수정
  src/main/java/com/meta/metaway/admin/dto/AdminOrderDTO.java
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/templates/admin/adminview.html
Labels: ✨ For: Backend, 🎨 For: Frontend, 👈 Priority: Middle, ✅ Status: Complete, 🔨 Type: Refactor

#165 주문 화면 css 수정
  src/main/resources/static/css/order.css
Labels: ⚙ For: API, 🎨 For: Frontend

#167 Feat: 로그 파일 주기적으로 삭제
  src/main/java/com/meta/metaway/admin/scheduler/LogCleanupScheduler.java
  src/main/java/com/meta/metaway/user/service/MailSendService.java
Labels: ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete, 🔨 Type: Refactor

#168 strrtadr 받아오도록 매퍼 수정
  src/main/resources/mapper/staff/StaffMapper.xml
  src/main/resources/mapper/user/UserMapper.xml
Labels: ⚙ For: API, ✨ For: Backend

#169 admin adress 부분 수정
  src/main/resources/mapper/admin/AdminMapper.xml
  src/main/resources/mapper/admin/AdminReturnMapper.xml
Labels: ⚙ For: API, ✨ For: Backend

#172 front
  src/main/resources/static/css/admin/style.css
  src/main/resources/static/css/join.css
  src/main/resources/templates/admin/ordermanager.html
Labels: 🎨 For: Frontend

#173 refactor: 좀더 보기 편하게 수정
  src/main/java/com/meta/metaway/global/PerformanceMonitoringAspect.java
  src/main/resources/templates/user/emailVerification.html
  src/main/resources/templates/user/join.html
Labels: ✨ For: Backend, 🎨 For: Frontend, 👇 Priority: Low, ✅ Status: Complete, 🔨 Type: Refactor

#174 refactor: 나머지 파일 변경된거 수정
  src/main/java/com/meta/metaway/global/PerformanceMonitoringAspect.java
  src/main/java/com/meta/metaway/user/service/MailSendService.java
  src/main/resources/templates/admin/productRankWithImage.html
Labels: 🎨 For: Frontend, 🔨 Type: Refactor

#175 HTML 어드민페이지 변경사항 반영, 쓰지않는 컨트롤러 메서드 제거
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/templates/admin/staffmanage.html
  src/main/resources/templates/staff/drive-todo.html
  src/main/resources/templates/user/orderDetail.html
Labels: ⚙ For: API, ✨ For: Backend, 🎨 For: Frontend

#176 드라이버, 코디 화면 변경
  src/main/resources/templates/staff/cody-todo.html
  src/main/resources/templates/staff/drive-todo.html
Labels: 🎨 For: Frontend, 👇 Priority: Low

#177 테스트케이스 목록 푸쉬
  src/test/java/com/meta/metaway/admin/service/AdminStaffServiceTest.java
  src/test/java/com/meta/metaway/order/service/OrderServiceTest.java
  src/test/java/com/meta/metaway/product/service/ProductServiceTest.java
  src/test/java/com/meta/metaway/returned/service/RetrunedServiceTest.java
  src/test/java/com/meta/metaway/schedule/service/ScheduleServiceTest.java
  src/test/java/com/meta/metaway/staff/service/StaffServiceTest.java
  src/test/java/com/meta/metaway/user/service/UserServiceTest.java
Labels: ✅ For: Test, ✨ For: Backend, 👈 Priority: Middle

#180 업무 완료시 얼럿 추가 + 컨트롤러 try catch 추가
  src/main/java/com/meta/metaway/user/controller/UserController.java
  src/main/resources/mapper/admin/AdminStaffMapper.xml
  src/main/resources/static/css/order.css
  src/main/resources/templates/admin/orderdetail.html
  src/main/resources/templates/admin/ordermanager.html
  src/main/resources/templates/order/order.html
  src/main/resources/templates/staff/cody-todo.html
  src/main/resources/templates/staff/drive-todo.html
Labels: ✨ For: Backend, 🎨 For: Frontend

#181 HTML 얼럿 추가
  src/main/resources/templates/staff/cody-todo.html
  src/main/resources/templates/staff/drive-todo.html
Labels: 🎨 For: Frontend

#182 코디-투두 html 변경
  src/main/resources/templates/staff/cody-todo.html
Labels: 🎨 For: Frontend
